### ISSUE TITLE
Missing exercises

### ISSUE THREAD

**Issue by abauville** [abauville/lickwars#122]
Some exercises don't show up in the exercise index. For testing, I removed all other exercises from the seed but warmup melody and twinkle. Warmup shoes up, but none of the filters show twinkle. I was connected as Tom and the Sarah is the teacher for those exercises.

Also, maybe related, Sarah can see her own exercises in the teacher's index page but not in the normal one

<img width="777" alt="Screen Shot 2022-03-09 at 19 36 58" src="https://user-images.githubusercontent.com/39847270/157426195-83f9023f-287a-4b71-870f-ede3b4008bb6.png">

Some details that might be helpful for debugging
<img width="474" alt="Screen Shot 2022-03-09 at 19 37 58" src="https://user-images.githubusercontent.com/39847270/157425100-e6414249-10d1-4d74-8ea0-ce12d627c25b.png">

Details of the question of the Warmup melody
<img width="548" alt="Screen Shot 2022-03-09 at 19 38 32" src="https://user-images.githubusercontent.com/39847270/157425185-80babd12-0438-47e6-8bba-b2ed3b900db1.png">

Details of the question for Twinkle
<img width="677" alt="Screen Shot 2022-03-09 at 19 42 01" src="https://user-images.githubusercontent.com/39847270/157425819-f7f83609-69b1-455d-b5c4-3deaf0723278.png">

**Comment by markiecyt** [comment]
This was a good find. 

So the exercise all and by difficulty queries were working as expected.
- returning all the exercises not by the current user, and which the current user hasn't attempted
- returning filtered by level and above conditions

The musics query had an issue because it was returning exercises by current user.
Will push a solution.
